import type { RepoContext, OutputProfile } from "../types.js";

export function renderMarkdown(
  context: RepoContext,
  profile: OutputProfile = "default"
): string {
  const lines: string[] = [];

  lines.push(`# Repository Context`);
  lines.push("");
  lines.push(`Generated by \`repo-context\`.`);
  lines.push("");
  lines.push(`## Project`);
  lines.push("");
  lines.push(`- Name: \`${context.projectName}\``);
  lines.push(`- Root: \`${context.rootPath}\``);
  lines.push(`- Generated at: \`${context.generatedAt}\``);
  lines.push("");

  lines.push(`## Purpose`);
  lines.push("");
  lines.push(
    `This file provides a compact, structured summary of the repository for AI coding assistants.`
  );
  lines.push(
    `It is generated locally and does not require sending the whole codebase to an AI model.`
  );
  lines.push("");

  renderListSection(lines, "Detected Stack", context.detectedStack);
  renderListSection(lines, "Package Managers", context.packageManagers);

  lines.push(`## Folder Structure`);
  lines.push("");
  lines.push("```txt");
  lines.push(context.folderTree);
  lines.push("```");
  lines.push("");

  lines.push(`## Important Files`);
  lines.push("");

  if (context.importantFiles.length === 0) {
    lines.push(`No important files detected.`);
  } else {
    for (const file of context.importantFiles) {
      lines.push(`- \`${file.path}\`: ${file.reason}`);
    }
  }

  lines.push("");

  lines.push(`## Available Commands`);
  lines.push("");

  if (context.commands.length === 0) {
    lines.push(`No commands detected.`);
  } else {
    for (const command of context.commands) {
      const description = command.description
        ? ` — ${command.description}`
        : "";
      lines.push(
        `- \`${command.command}\` from \`${command.source}\`${description}`
      );
    }
  }

  lines.push("");

  renderListSection(
    lines,
    "Environment Variables",
    context.environmentVariables.map((variable) => `\`${variable}\``)
  );

  lines.push(`## Notes`);
  lines.push("");

  if (context.notes.length === 0) {
    lines.push(`- No additional notes.`);
  } else {
    for (const note of context.notes) {
      lines.push(`- ${note}`);
    }
  }

  lines.push("");

  lines.push(`## Suggested AI Prompt`);
  lines.push("");
  lines.push("```txt");
  lines.push(getSuggestedPrompt(profile));
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

function renderListSection(
  lines: string[],
  title: string,
  items: string[]
): void {
  lines.push(`## ${title}`);
  lines.push("");

  if (items.length === 0) {
    lines.push(`None detected.`);
  } else {
    for (const item of items) {
      lines.push(`- ${item}`);
    }
  }

  lines.push("");
}

function getSuggestedPrompt(profile: OutputProfile): string {
  if (profile === "claude") {
    return [
      "You are helping me work on this repository.",
      "Use the repository context below to understand the architecture, stack, commands, and important files.",
      "Before suggesting code changes, reason about which files are likely relevant and explain why.",
      "Ask for the contents of specific files when you need them instead of guessing."
    ].join("\n");
  }

  if (profile === "cursor") {
    return [
      "Use this repository context as project-level guidance.",
      "Prefer small, focused changes that fit the existing structure.",
      "Follow the detected stack, commands, and conventions shown below."
    ].join("\n");
  }

  if (profile === "codex") {
    return [
      "You are working as a coding agent inside this repository.",
      "Use the context below to identify the stack, commands, entry points, and likely files to edit.",
      "Make minimal, safe, testable changes and verify them with the listed commands."
    ].join("\n");
  }

  return [
    "You are helping me work on this repository.",
    "Use the following context to understand the project structure, stack, commands, and important files before suggesting changes.",
    "Do not assume missing details. If something is unclear, ask for the relevant file or command output."
  ].join("\n");
}
