export const DEFAULT_OUTPUT_FILE = "repo-context.md";

export const DEFAULT_MAX_DEPTH = 4;

export const DEFAULT_IGNORE_PATTERNS = [
  ".git/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  "bin/**",
  "obj/**",
  ".next/**",
  ".nuxt/**",
  ".cache/**",
  "coverage/**",
  ".venv/**",
  "venv/**",
  "__pycache__/**",
  ".idea/**",
  ".vscode/**",
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.webp",
  "*.mp4",
  "*.mov",
  "*.pdf",
  "*.zip",
  "*.tar",
  "*.gz",
  ".env"
];

export const IMPORTANT_FILE_PATTERNS = [
  "README.md",
  "readme.md",
  "package.json",
  "pyproject.toml",
  "requirements.txt",
  "Pipfile",
  "poetry.lock",
  "Cargo.toml",
  "go.mod",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  "Makefile",
  "*.sln",
  "*.csproj",
  "*.fsproj",
  "*.vbproj",
  "*.addin",
  ".env.example",
  ".env.sample",
  "tsconfig.json",
  "vite.config.ts",
  "next.config.js",
  "next.config.mjs"
];
